# Monorepo tags - add a dedicated tag for each repository in the monorepo

name: Monorepo PR Labeler

on: pull_request

jobs:
  labelPR:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
